all:
	pdflatex lecture
	pdflatex lecture
	@echo "pdftk A=lecture.pdf cat A1-7 output info.pdf"
	@echo "pdftk A=lecture.pdf cat A8-27 output unit01.pdf"
	@echo "pdftk A=lecture.pdf cat A28-41 output unit02.pdf"
	@echo "pdftk A=lecture.pdf cat A42-57 output unit03.pdf"
	@echo "pdftk A=lecture.pdf cat A58-69 output unit04.pdf"
	@echo "pdftk A=lecture.pdf cat A70-81 output unit05.pdf"
	@echo "pdftk A=lecture.pdf cat A82-91 output unit06.pdf"
	@echo "pdftk A=lecture.pdf cat A92-102 output unit07.pdf"
	@echo "pdftk A=lecture.pdf cat A103-112 output unit08.pdf"
	@echo "pdftk A=lecture.pdf cat A113-121 output unit09.pdf"
	@echo "pdftk A=lecture.pdf cat A122-137 output unit10.pdf"
	@echo "pdftk A=lecture.pdf cat A138-148 output unit11.pdf"
