all:
	pdflatex lecture
	pdflatex lecture
	@echo "pdftk A=lecture.pdf cat A1-6 output info.pdf"
	@echo "pdftk A=lecture.pdf cat A7-26 output unit01.pdf"
	@echo "pdftk A=lecture.pdf cat A27-40 output unit02.pdf"
